# Generated by Django 4.2.6 on 2023-10-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table_entries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data1', models.IntegerField(null=True)),
                ('data2', models.IntegerField(null=True)),
                ('data3', models.IntegerField(null=True)),
                ('data4', models.IntegerField(null=True)),
                ('data5', models.IntegerField(null=True)),
                ('data6', models.IntegerField(null=True)),
                ('data7', models.IntegerField(null=True)),
                ('data8', models.IntegerField(null=True)),
                ('data9', models.IntegerField(null=True)),
            ],
        ),
    ]
