# Generated by Django 4.2.6 on 2023-10-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Fellowship_No', models.CharField(max_length=20)),
                ('PI_of_Project', models.CharField(max_length=20)),
                ('Sanctioned_Date', models.DateField()),
                ('Project_Start_Date', models.DateField()),
                ('Project_Closure_Date', models.DateField()),
                ('Title_of_Project', models.CharField(max_length=50)),
            ],
        ),
    ]
