# Generated by Django 5.0.1 on 2024-01-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_project_details_end_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_details',
            name='task',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=10),
        ),
    ]
