# Generated by Django 4.2.6 on 2023-10-22 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_table_data_delete_table_entries'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='table_data',
            new_name='table_entries',
        ),
    ]
