# Generated by Django 4.2.6 on 2024-01-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_project_details_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_details',
            name='funding_agency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
