# Generated by Django 4.2.6 on 2024-01-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_project_details_funding_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_details',
            name='Co_PI_of_Project',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
