# Generated by Django 4.2.6 on 2023-10-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_table_info_delete_table_entries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_details',
            name='PI_of_Project',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project_details',
            name='Project_Fellowship_No',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project_details',
            name='Title_of_Project',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
