# Generated by Django 4.2.6 on 2023-10-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_project_details_pi_of_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_details',
            name='Project_Closure_Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project_details',
            name='Project_Start_Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project_details',
            name='Sanctioned_Date',
            field=models.DateField(null=True),
        ),
    ]
