# Generated by Django 5.0.1 on 2024-01-23 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_project_details_co_pi_of_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_details',
            name='Co_PI_of_Project',
        ),
        migrations.RemoveField(
            model_name='project_details',
            name='funding_agency',
        ),
    ]
