# Generated by Django 5.0.1 on 2024-01-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_project_details_co_pi_of_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_details',
            name='Co_PI_of_Project',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project_details',
            name='funding_agency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
