# Generated by Django 5.0.1 on 2024-01-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_project_details_co_pi_of_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_details',
            name='Category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project_details',
            name='Country_Involved',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project_details',
            name='Details_of_Donors',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project_details',
            name='audited_uc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project_details',
            name='date_of_receipt_amount',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project_details',
            name='fellowship_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project_details',
            name='link_uc',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project_details',
            name='provisional_uc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project_details',
            name='received_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project_details',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project_details',
            name='sanction_letters_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project_details',
            name='scheme_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project_details',
            name='scheme_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project_details',
            name='total_project_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
