# Generated by Django 4.2.6 on 2024-01-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_table_info_total_apr_table_info_total_aug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_details',
            name='id',
        ),
        migrations.AlterField(
            model_name='project_details',
            name='Project_Fellowship_No',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
