# Generated by Django 5.0.1 on 2024-01-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_project_details_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_details',
            name='Department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
