# Generated by Django 4.2.6 on 2024-01-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_project_details_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_details',
            name='financial_year_end_index',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='project_details',
            name='financial_year_start_index',
            field=models.IntegerField(null=True),
        ),
    ]
