# Generated by Django 5.0.1 on 2024-01-27 12:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_project_details_received_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_details',
            name='date_of_receipt_amount',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
