# Generated by Django 4.2.6 on 2024-03-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_project_details_date_of_receipt_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_details',
            name='Country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
