# Generated by Django 4.2.6 on 2024-04-03 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_project_details_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='table_info',
        ),
    ]
